name: Update Translations

on:
  workflow_dispatch:

jobs:
  translation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: transifex/cli-action@v2
        with:
          token: ${{ secrets.TRANSIFEX_TOKEN }}
          args: pull -a --force
      - run: |
          git config --global user.name "Traccar Bot"
          git config --global user.email "support@traccar.org"
          git add src/resources/l10n/*.json ':!src/resources/l10n/en.json'
          git diff --cached --quiet || git commit -m "Update translations"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
